import {BACKGROUND_COLOR, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN} from "./settings";

export const one = ([
    [ONE, ONE, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [ONE, ONE, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);

export const two = ([
    [TWO, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [TWO, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [TWO, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [TWO, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);

export const three = (
    [[BACKGROUND_COLOR, THREE, THREE, BACKGROUND_COLOR],
    [THREE, THREE, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]]
);

export const four = ([
    [FOUR, FOUR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, FOUR, FOUR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);

export const five = ([
    [BACKGROUND_COLOR, FIVE, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [FIVE, FIVE, FIVE, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);

export const six = ([
    [SIX, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [SIX, SIX, SIX, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);

export const seven = ([
    [BACKGROUND_COLOR, BACKGROUND_COLOR, SEVEN, BACKGROUND_COLOR],
    [SEVEN, SEVEN, SEVEN, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR],
    [BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR, BACKGROUND_COLOR]
    ]);